import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NextAuthSessionProvider from '@/components/Providers/NextAuthSessionProvider';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthSessionProvider>
      <html lang="uz">
        <body
          className={`${inter.className} bg-gray-950 font-inter text-base text-gray-200 antialiased`}
        >
          {children}
        </body>
      </html>
    </NextAuthSessionProvider>
  );
}
